config/routes.rb
Rails.application.routes.draw do

  get '/' => 'sessions#new' 

  resources :users

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  resources :polls do
    member do
      get 'finalize'
    end
  end

  get '/polls/:id/invite' => 'polls#invite'
  post '/polls/:id/invite' => 'polls#invite_create'
  patch '/polls/:id/invite' => 'polls#invite_update'

  post '/polls/:id/appts/:appt_id' => 'polls#choose'

  get '/polls/:poll_id/users' => 'polls#edit'
  post '/polls/:poll_id' => 'polls#create'
  patch '/polls/:poll_id/users' => 'polls#update'

  resources :appts
  get '/appts/:poll_id' => 'appts#new'
  post '/appts' => 'appts#create'
  patch '/appts/:poll_id' => 'appts#create'

  resources :responses
  # get '/responses' => 'responses#index'
  # get '/responses/new' => 'responses#new'
  # post '/responses' => 'responses#create'
  # get '/responses/:id' => 'responses#show'
  # get '/responses/:id/edit' => 'responses#edit'
  # patch '/responses/:id' => 'responses#update'
  # delete '/responses/:id' => 'responses#destroy'

  post '/userpolls' => 'userpolls#create'

  get '/pages' => 'pages#index'
  get '/pages/:id' => 'pages#show' 

  get '/mailers/:id' => 'mailers#show'
end

app/models/poll.rb
class Poll < ApplicationRecord
  belongs_to :user, foreign_key: "admin_id"
  has_many :userpolls
  has_many :users, through: :userpolls
  has_many :appts
  has_many :responses

  # validates :title, presence: true
  # validates :status, presence: true
  # validates :invitee, presence: true
  # validates :location, presence: true

  def invite(invitees)
    emails = invitees.gsub(" ", "").split(",")

    emails.each do |email|
      user = User.find_by(email: email)

      if user
        Userpoll.find_or_create_by!(user_id: user.id, poll_id: id)
      end
    end
  end

  def finalized?
    appts.where(chosen: true).any?
  end

  def final_time
    appts.find_by(chosen: true).friendly_slot
  end
end

app/controllers/polls_controller.rb
class PollsController < ApplicationController
  before_action :authenticate_user!

  def index
    @polls = Poll.where(admin_id: current_user.id)
    @response_polls = current_user.polls
  end

  def new
    @poll = Poll.new
  end

  def create
    @poll = Poll.new(
                    admin_id: current_user.id,
                    title: params[:title],
                    status: "In progress",
                    address: params[:address],
                    city: params[:city],
                    state: params[:state]
                    )
    if @poll.save
      #current_user.save
      # we have poll.id here to send to email
      # put in email method here, passing in poll.id
      @poll.invite(params[:invitees])
      redirect_to "/appts/new?poll_id=#{@poll.id}"
    else
      flash[:warning] = "Unable to save."
      render 'new.html.erb'
    end
  end

  def show
    @poll = Poll.find(params[:id])
  end

  def edit
    @poll = Poll.find(params[:id])
  end

  def user_edit
    @poll = Poll.find(params[:id])
  end

  def update
    poll = Poll.find(params[:id])
    poll.assign_attributes(
                          title: params[:title],
                          address: params[:address],
                          city: params[:city],
                          state: params[:state],
                          )
    poll.save
    flash[:success] = "Changes successfully saved."
    redirect_to "/polls/#{poll.id}"
  end

  def finalize
    @poll = Poll.find(params[:id])
  end

  def invite
    @poll = Poll.find(params[:id])
  end

  def invite_create
    @poll = Poll.find(params[:id])
    @poll.invite(params[:invitees])
    redirect_to "/polls"
  end

  def invite_update
    @poll = Poll.find(params[:id])
    @poll.invite(params[:invitees])

    flash[:success] = "Invitee(s) successfully added."
    redirect_to "/polls"
  end

  def choose
    @poll = Poll.find(params[:id])
    @appt = Appt.find(params[:appt_id])

    @poll.appts.update_all(chosen: false)
    @appt.update(chosen: true)

    flash[:success] = "Meeting time successfully finalized. We're emailing your invitees now."
    redirect_to "/polls"
  end

  # def survey

  # end

  def destroy
    poll = Poll.find(params[:id])
    poll.destroy
    flash[:warning] = "Meeting deleted."
    redirect_to "/polls"
  end
end

app/helpers/polls_helper.rb
module PollsHelper
  def status_list
    ["In Progress", "Finalized"]
  end
  
  def states_list
  [
    ['AK', 'AK'],
    ['AL', 'AL'],
    ['AR', 'AR'],
    ['AZ', 'AZ'],
    ['CA', 'CA'],
    ['CO', 'CO'],
    ['CT', 'CT'],
    ['DC', 'DC'],
    ['DE', 'DE'],
    ['FL', 'FL'],
    ['GA', 'GA'],
    ['HI', 'HI'],
    ['IA', 'IA'],
    ['ID', 'ID'],
    ['IL', 'IL'],
    ['IN', 'IN'],
    ['KS', 'KS'],
    ['KY', 'KY'],
    ['LA', 'LA'],
    ['MA', 'MA'],
    ['MD', 'MD'],
    ['ME', 'ME'],
    ['MI', 'MI'],
    ['MN', 'MN'],
    ['MO', 'MO'],
    ['MS', 'MS'],
    ['MT', 'MT'],
    ['NC', 'NC'],
    ['ND', 'ND'],
    ['NE', 'NE'],
    ['NH', 'NH'],
    ['NJ', 'NJ'],
    ['NM', 'NM'],
    ['NV', 'NV'],
    ['NY', 'NY'],
    ['OH', 'OH'],
    ['OK', 'OK'],
    ['OR', 'OR'],
    ['PA', 'PA'],
    ['RI', 'RI'],
    ['SC', 'SC'],
    ['SD', 'SD'],
    ['TN', 'TN'],
    ['TX', 'TX'],
    ['UT', 'UT'],
    ['VA', 'VA'],
    ['VT', 'VT'],
    ['WA', 'WA'],
    ['WI', 'WI'],
    ['WV', 'WV'],
    ['WY', 'WY']
  ]
  end

end

app/views/polls/edit.html.erb
<section>
  <div class="row">
    <div class="col-sm-8 col-sm-offset-2">
      <div class="user_single">
        <div class="well">
          <div class="edit">
            <h1>Edit Meeting</h1>
            </div>
            <p>Make changes to details about your meeting, delete time options, add invitees, or delete the meeting.</p>
            <div class="form-group">
              <p>Times</p>
              <ul>
                <% @poll.appts.each do |appt| %>
                <div class="bullet">
                  <li><p><%= link_to appt.friendly_slot + " - Delete", "/appts/#{appt.id}", {method: :delete } %></p></li></div>
                <% end %>
              </ul>
            </div>

            <%= form_tag "/polls/#{@poll.id}", method: :patch do %>

              <div class="form-group">
              <p>Title <input type="text" name="title" value="<%= @poll.title %>"></p>
              </div>
            
              <div class="form-group">
              <!--   <%= label_tag :address %> -->
              <p>Address <%= text_field_tag :address, @poll.address, class: "form-control" %></p>
              </div>
              <div class="form-group">
               <!--  # <%= label_tag :city %> -->
              <p>City <%= text_field_tag :city, @poll.city, class: "form-control" %></p>
              </div>
              <div class="form-group">
               <!--  <%= label_tag :state %> -->
              <p>State <%= select_tag :state, options_for_select(states_list, @poll.state) %></p>
              </div>
          <!-- <div class="form-group">
          Invitee Email: <input type="text" name="email" value="<%= @poll.user.email %>">
          </div> -->

              <div class="form-group">
                <%= hidden_field_tag :poll_response_id, @poll_response_id %>
              <p>Invite List <%= email_field_tag :email, @poll.user.email, class: "form-control" %></p>
              </div>
      
              <%= submit_tag "Save Changes", class: "btn btn-success" %>
          
         <!--  <input type="submit" value="Save Changes">  --> 
              <% if @poll.user.id == current_user.id %>
                <%= link_to "Delete Meeting", "/polls/#{@poll.id}", {method: :delete,  class: "btn btn-danger" }%>
              <% end %>
            <% end %>
          </div>
        </div>
      
    </div>
  </div>
</section>


     

app/views/polls/finalize.html.erb
<section>
  <div class="row">
    <div class="col-sm-8 col-sm-offset-2">
      <div class="poll_response">
      <div class="well" align="center">
      <h3>Select a meeting time from invitees' responses: </h3><br>
        <table>
            <tr>
              <th>Time</th>
              <th>Yes</th>
              <th>No</th>
              <th>Maybe</th>
              <th>Finalize?</th>
            </tr>
            <% @poll.appts.each do |appt| %>
              <tr>
                <td><%= appt.friendly_slot %></td>
                <td><%= appt.yes_count %></td>            
                <td><%= appt.no_count %></td>            
                <td><%= appt.maybe_count %></td> 
                <td><%= link_to "Finalize", "/polls/#{@poll.id}/appts/#{appt.id}", method: :post %></td>           
              </tr>
            <% end %>
          </table>
          <div>
          <br>
          <h3>Ready for another meeting? <%= link_to "Create meeting", new_poll_url, class: "btn btn-success" %>  <%= link_to "Home", polls_url, class: "btn btn-primary" %></h3>
          </div>
            
        </div>
      </div>
    </div>
  </div>
</section>

app/views/polls/index.html.erb
<section>
  <div class="row">
    <div class="col-md-12">
    <div class="column-left">
      <div class="thumbnail well">
        <h2> Meetings You Created </h2>
        <p>Click on a meeting name to view its details.</p>
        <% if @polls.empty? %>
          <p>You have no meetings created yet.<br><%= link_to "Create meeting", new_poll_url, class: "btn btn-primary" %></p>
        <% end %>
          <% @polls.each do |poll| %>
            <ul style="list-style-type:none">
                <li><h4>                                              
                    <%= link_to poll.title, "/polls/#{poll.id}", class: "title" %> <%= link_to "Edit", edit_poll_url(poll), class: "btn btn-warning button" %>
                    <% if poll.user.id == current_user.id %>
                      <%= link_to "Invite", "/polls/#{poll.id}/invite", class: "btn btn-primary" %>
                      <%= link_to "Responses", "/polls/#{poll.id}/finalize", class: "btn btn-success" %></h4></li>
                  <% end %>
            </ul>           
          <% end %>
      </div>
    </div>
    
    <div class="column-right">
      <div class="thumbnail well">
        <h2> You've Been Invited </h2>
        <p>Click an RSVP button to see event details.</p>
          <ul style="list-style-type:none">
            <% @response_polls.each do |response_poll| %>
              <li><h4 style="font-weight: 600;"><%= response_poll.title %>
                      <%= link_to "RSVP", "/polls/#{response_poll.id}", class: "btn btn-primary" %></h4></li>
            <% end %>
          </ul>
      </div>
    </div>
  </div>
</section>

app/views/polls/invite.html.erb
<section>
  <div class="row">
    <div class="col-sm-8 col-sm-offset-2">
      <div class="user_single">
        <div class="well">
          <h1 style="color: #ffffff;">Invite More People</h1>
            <%= form_tag "/polls/#{@poll.id}/invite", method: :patch do %>
            <div class="form-group">
              <p>Please enter a list of emails separated by commas.</p>
              <p>Add to Invite List <%= text_field_tag :invitees, nil, class: "form-control" %></p>
              </div>
                <%= submit_tag "Save", class: "btn btn-success" %>
            <% end %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/polls/new.html.erb
<section>
  <div class="row">
    <div class="col-sm-8 col-sm-offset-2">
      <div class="user_single">
        <div class="well">
          <h1 style="color: #ffffff;">Create a Meeting</h1>
            <%= form_tag '/polls', method: :post do %>
            <div class="form-group">
              <!-- # <%= label_tag :title %> -->
            <p>Title <%= text_field_tag :title, nil, class: "form-control" %></p>
            </div>
            <div class="form-group">
              <!-- # <%= label_tag :address %> -->
            <p>Address <%= text_field_tag :address, nil, class: "form-control" %></p>
            </div>
            <div class="form-group">
              <!-- # <%= label_tag :city %> -->
            <p>City <%= text_field_tag :city, nil, class: "form-control" %></p>
            </div>
            <div class="form-group">
              <!-- # <%= label_tag :state %> -->
            <p>State <%= select_tag :state, options_for_select(states_list, "IL") %></p>
            </div><br>
            <div class="form-group">
              <p>Please enter a list of emails separated by commas.</p>
              <p>Invite List <%= text_field_tag :invitees, nil, class: "form-control" %></p>
            </div>
              <%= submit_tag "Save", class: "btn btn-success" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/polls/show.html.erb
<section>
  <div class="row">
    <div class="col-sm-8 col-sm-offset-2">
      <div class="user_single">
        <div class="well">
            <h1 style="color: #ffffff;">Meeting Details</h1>
            <p>Title: <%= @poll.title %></p>
            <p>Address: <%= @poll.address %></p>
            <p>City: <%= @poll.city %></p>
            <p>State: <%= @poll.state %></p>
    
            <div class="form-group">
                <%= hidden_field_tag :poll_response_id, @poll_response_id %>
              <p>Invitee List: <%= email_field_tag :email, @poll.user.email, class: "form-control" %></p>
            </div>
            
            <% if @poll.finalized? %>
              <h3 class="red"><%= @poll.final_time %></h3>
              <p>This meeting time has been finalized.</p>
              <% if current_user.id == @poll.admin_id %>
                <p>Ready for another meeting? <%= link_to "New", new_poll_url, class: "btn btn-primary" %></p>
              <% end %>
            <% else %>
              <h3>Time(s)</h3>
              <% if current_user.id == @poll.admin_id %>
                <% @poll.appts.each do |appt| %>
                  <p><%= appt.friendly_slot %></p>
                <% end %>
              
                <%= link_to "Add Another Time Option", "/appts/new?poll_id=#{@poll.id}", class: "btn btn-warning" %>
                <%= link_to "View Responses", "/polls/#{@poll.id}/finalize", class: "btn btn-primary" %>

              <% else %>
                <%= form_tag "/responses", method: :post do %>
                  <%= hidden_field_tag :poll_id, @poll.id %>
                  <% @poll.appts.each do |appt| %>
                    <div>
                      <%= appt.scheduled_slot.strftime('%A - %B %e, %l:%M %p') %> - 
                      <select name="appts[<%= appt.id %>]">
                        <option value="Yes">Yes</option>
                        <option value="No">No</option>
                        <option value="Maybe">Maybe</option>
                      </select>
                    </div>
                    <br>
                  <% end %>

                  <%= submit_tag "Send Responses", class: "btn btn-primary" %>
                <% end %>
              <% end %>
            <% end %>
          </div>
      </div>
    </div>
  </div>
</section>

app/views/polls/user_edit.html.erb
<h3>MeetMe Poll</h3>

<%= form_tag '/polls/:poll_id/users', method: :post do %>
  <div>
    <select name="Meeting Option 1">
      <option value="Yes">Yes</option>
      <option value="No">No</option>
      <option value="Maybe">Maybe</option>
    </select>
  </div>
    
<div>
    <select name="Meeting Option 2">
      <option value="Yes">Yes</option>
      <option value="No">No</option>
      <option value="Maybe">Maybe</option>
    </select>
  </div>
    
<div>
    <select name="Meeting Option 3">
      <option value="Yes">Yes</option>
      <option value="No">No</option>
      <option value="Maybe">Maybe</option>
    </select>
  </div>
   
<div>
    <select name="Meeting Option 4">
      <option value="Yes">Yes</option>
      <option value="No">No</option>
      <option value="Maybe">Maybe</option>
    </select>
  </div>
    <%= submit_tag "Save" %>
<% end %>


<!-- get '/polls/:poll_id/users' => 'polls#edit' -->